### PR TITLE
Godot 4.0 Vulkan support

### PR DESCRIPTION
**Pull request by Ozzadar**
- Updated `rapidjson` library
- Maintains compatibility for Godot <4

### CODE REVIEW

**Comment by Ranoller** [comment]
Ok, i didn´t see your pull request... you do a lot of work!. If you allow to merge that, i will, and test in 3.0 - 3.2

**Comment by Ozzadar** [comment]
Ive actually decided to maintain this in my own fork; I opened the PR here by accident.

You had mentioned that you dont even use this anymore; and I'm probably going to start adding features to it.

Additionally, I had to make some changes for  <4.0 builds; im testing them now.

https://github.com/mauville-technologies/godot-dragonbones

I also changed the repo name so that people can find it easier using Google

**Comment by Ranoller** [comment]
Ok, it´s the correct way. I will add in this fork a link to your fork if you wan´t to consider the current maintained, and if in a future i return to use dragon bones in a godot project, and need any change i pull to your fork. Good work. It´s good to know that this plugin will not be forgotten.

**Comment by Ozzadar** [comment]
In the future if you have time for it I can always add you as a collaborator on the organization repo. This way we don't need to play repo tag in the future as we keep things maintained

**Comment by Ranoller** [comment]
Thanks, if i return to work with this i will aks to you. I spam today a lot on the web to get the users correct pointed. I think that now it´s clear what plugin use in every circumstance, and is clear that your fork is the current maintained for godot 3.1+. I will maintain this pull request opened but not merged (If you don´t have problem with that) for the case that you or other want to test differences before/after your commits of today. You (or others) can use this fork to test differences. First result of google have now info about your fork, and i hope that current users can find that.

**Pull request closed without merging**
